-- MySQL Script generated by MySQL Workbench
-- Fri May 22 19:20:43 2020
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema spotifydb
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema spotifydb
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `spotifydb` DEFAULT CHARACTER SET utf8 ;
USE `spotifydb` ;

-- -----------------------------------------------------
-- Table `spotifydb`.`artists`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `spotifydb`.`artists` (
  `alpha2` VARCHAR(2) NOT NULL,
  `alpha3` VARCHAR(3) NOT NULL,
  `name` VARCHAR(45) NOT NULL,
  `genre` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`alpha2`))
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;


-- -----------------------------------------------------
-- Data for table `spotifydb`.`artists`
-- -----------------------------------------------------
START TRANSACTION;
USE `spotifydb`;
INSERT INTO `spotifydb`.`artists` (`alpha2`, `alpha3`, `name`, `genre`) VALUES ('DE', 'DEU', 'Kygo', 'Pop');

COMMIT;

